-- 0001_users.sql
--
-- PROVISIONAL. This is the smallest possible users table, there only so the st_*
-- foreign keys (created_by, assigned_user_id, requested_by_user_id, ...) have
-- something to point at. The ERP auth/core work owns this table. It should extend
-- it with ALTER TABLE (PIN hash, salt, firm access and so on, see PLAN.md §4)
-- rather than recreate it.
--
-- No users and no passwords are seeded here, or in any migration.
--
-- Conventions used by every migration in this folder:
--   * ids are TEXT and generated by the app (UUID). They are never derived from names.
--   * timestamps are UTC ISO-8601 text, e.g. 2026-10-01T09:24:00.000Z.
--   * calendar dates are 'YYYY-MM-DD' text.
--   * money is INTEGER paise.
--   * soft delete: deleted_at IS NULL means the row is live. The repos set updated_at.
--   * nothing here has been run. It is applied at DB-connect time (docs/DB-CONNECT-LATER.md).

CREATE TABLE users (
  id            TEXT PRIMARY KEY,
  username      TEXT NOT NULL COLLATE NOCASE,
  name          TEXT NOT NULL,
  email         TEXT,
  phone         TEXT,
  department    TEXT,
  role          TEXT NOT NULL,              -- e.g. superadmin | admin | dispatch | marketing | management
  status        TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
  password_hash TEXT,                       -- never plaintext
  created_by    TEXT REFERENCES users(id),
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  deleted_at    TEXT
);

CREATE UNIQUE INDEX users_username_uq ON users (username) WHERE deleted_at IS NULL;
CREATE INDEX users_role_idx ON users (role);
