-- 0003_sampletrack_seed.sql
--
-- Reference data for SampleTrack. Taken from legacy/sampletrack/index.html:
--   * 36 states/UTs (INDIAN_STATES), with their GST state codes added
--   * 109 cities (INDIAN_CITIES with the duplicate 'Ghaziabad' removed) and their
--     states from cityStateMap. All have is_custom = 0.
--   * the 6 sample products from seedData(); prices converted from rupees to paise
--   * default settings and the REQ/DSP counters
--
-- NO users and NO passwords are seeded here. Parties, couriers, requests and
-- dispatches are demo data. They go in the dev-only in-memory seed (/api/src/seed),
-- not in a migration.
--
-- Legacy "Dadra & Nagar Haveli" is stored as the merged UT
-- "Dadra & Nagar Haveli and Daman & Diu" (GST code 26).

INSERT INTO st_states (id, name, gst_code, kind) VALUES
  ('state-01', 'Jammu & Kashmir', '01', 'UT'),
  ('state-02', 'Himachal Pradesh', '02', 'State'),
  ('state-03', 'Punjab', '03', 'State'),
  ('state-04', 'Chandigarh', '04', 'UT'),
  ('state-05', 'Uttarakhand', '05', 'State'),
  ('state-06', 'Haryana', '06', 'State'),
  ('state-07', 'Delhi', '07', 'UT'),
  ('state-08', 'Rajasthan', '08', 'State'),
  ('state-09', 'Uttar Pradesh', '09', 'State'),
  ('state-10', 'Bihar', '10', 'State'),
  ('state-11', 'Sikkim', '11', 'State'),
  ('state-12', 'Arunachal Pradesh', '12', 'State'),
  ('state-13', 'Nagaland', '13', 'State'),
  ('state-14', 'Manipur', '14', 'State'),
  ('state-15', 'Mizoram', '15', 'State'),
  ('state-16', 'Tripura', '16', 'State'),
  ('state-17', 'Meghalaya', '17', 'State'),
  ('state-18', 'Assam', '18', 'State'),
  ('state-19', 'West Bengal', '19', 'State'),
  ('state-20', 'Jharkhand', '20', 'State'),
  ('state-21', 'Odisha', '21', 'State'),
  ('state-22', 'Chhattisgarh', '22', 'State'),
  ('state-23', 'Madhya Pradesh', '23', 'State'),
  ('state-24', 'Gujarat', '24', 'State'),
  ('state-26', 'Dadra & Nagar Haveli and Daman & Diu', '26', 'UT'),
  ('state-27', 'Maharashtra', '27', 'State'),
  ('state-29', 'Karnataka', '29', 'State'),
  ('state-30', 'Goa', '30', 'State'),
  ('state-31', 'Lakshadweep', '31', 'UT'),
  ('state-32', 'Kerala', '32', 'State'),
  ('state-33', 'Tamil Nadu', '33', 'State'),
  ('state-34', 'Puducherry', '34', 'UT'),
  ('state-35', 'Andaman & Nicobar Islands', '35', 'UT'),
  ('state-36', 'Telangana', '36', 'State'),
  ('state-37', 'Andhra Pradesh', '37', 'State'),
  ('state-38', 'Ladakh', '38', 'UT');

INSERT INTO st_city_master (id, city, state_id, is_custom) VALUES
  ('city-agra', 'Agra', 'state-09', 0),
  ('city-ahmedabad', 'Ahmedabad', 'state-24', 0),
  ('city-ajmer', 'Ajmer', 'state-08', 0),
  ('city-allahabad', 'Allahabad', 'state-09', 0),
  ('city-ambala', 'Ambala', 'state-06', 0),
  ('city-amravati', 'Amravati', 'state-27', 0),
  ('city-amreli', 'Amreli', 'state-24', 0),
  ('city-amritsar', 'Amritsar', 'state-03', 0),
  ('city-anand', 'Anand', 'state-24', 0),
  ('city-ankleshwar', 'Ankleshwar', 'state-24', 0),
  ('city-asansol', 'Asansol', 'state-19', 0),
  ('city-aurangabad', 'Aurangabad', 'state-27', 0),
  ('city-bareilly', 'Bareilly', 'state-09', 0),
  ('city-belagavi', 'Belagavi', 'state-29', 0),
  ('city-bengaluru', 'Bengaluru', 'state-29', 0),
  ('city-bhagalpur', 'Bhagalpur', 'state-10', 0),
  ('city-bharuch', 'Bharuch', 'state-24', 0),
  ('city-bhavnagar', 'Bhavnagar', 'state-24', 0),
  ('city-bhilwara', 'Bhilwara', 'state-08', 0),
  ('city-bhopal', 'Bhopal', 'state-23', 0),
  ('city-bhubaneswar', 'Bhubaneswar', 'state-21', 0),
  ('city-bhuj', 'Bhuj', 'state-24', 0),
  ('city-bikaner', 'Bikaner', 'state-08', 0),
  ('city-chandigarh', 'Chandigarh', 'state-04', 0),
  ('city-chennai', 'Chennai', 'state-33', 0),
  ('city-coimbatore', 'Coimbatore', 'state-33', 0),
  ('city-dehradun', 'Dehradun', 'state-05', 0),
  ('city-delhi', 'Delhi', 'state-07', 0),
  ('city-dombivali', 'Dombivali', 'state-27', 0),
  ('city-durgapur', 'Durgapur', 'state-19', 0),
  ('city-faridabad', 'Faridabad', 'state-06', 0),
  ('city-gandhinagar', 'Gandhinagar', 'state-24', 0),
  ('city-gaya', 'Gaya', 'state-10', 0),
  ('city-ghaziabad', 'Ghaziabad', 'state-09', 0),
  ('city-gondal', 'Gondal', 'state-24', 0),
  ('city-greater-noida', 'Greater Noida', 'state-09', 0),
  ('city-gurgaon', 'Gurgaon', 'state-06', 0),
  ('city-guwahati', 'Guwahati', 'state-18', 0),
  ('city-gwalior', 'Gwalior', 'state-23', 0),
  ('city-howrah', 'Howrah', 'state-19', 0),
  ('city-hubballi', 'Hubballi', 'state-29', 0),
  ('city-hyderabad', 'Hyderabad', 'state-36', 0),
  ('city-indore', 'Indore', 'state-23', 0),
  ('city-jabalpur', 'Jabalpur', 'state-23', 0),
  ('city-jaipur', 'Jaipur', 'state-08', 0),
  ('city-jalandhar', 'Jalandhar', 'state-03', 0),
  ('city-jamnagar', 'Jamnagar', 'state-24', 0),
  ('city-jodhpur', 'Jodhpur', 'state-08', 0),
  ('city-junagadh', 'Junagadh', 'state-24', 0),
  ('city-kalaburagi', 'Kalaburagi', 'state-29', 0),
  ('city-kalyan', 'Kalyan', 'state-27', 0),
  ('city-kanpur', 'Kanpur', 'state-09', 0),
  ('city-karimnagar', 'Karimnagar', 'state-36', 0),
  ('city-khammam', 'Khammam', 'state-36', 0),
  ('city-kochi', 'Kochi', 'state-32', 0),
  ('city-kolhapur', 'Kolhapur', 'state-27', 0),
  ('city-kolkata', 'Kolkata', 'state-19', 0),
  ('city-kota', 'Kota', 'state-08', 0),
  ('city-kozhikode', 'Kozhikode', 'state-32', 0),
  ('city-latur', 'Latur', 'state-27', 0),
  ('city-lucknow', 'Lucknow', 'state-09', 0),
  ('city-ludhiana', 'Ludhiana', 'state-03', 0),
  ('city-madurai', 'Madurai', 'state-33', 0),
  ('city-mangaluru', 'Mangaluru', 'state-29', 0),
  ('city-meerut', 'Meerut', 'state-09', 0),
  ('city-mehsana', 'Mehsana', 'state-24', 0),
  ('city-morbi', 'Morbi', 'state-24', 0),
  ('city-mumbai', 'Mumbai', 'state-27', 0),
  ('city-muzaffarpur', 'Muzaffarpur', 'state-10', 0),
  ('city-mysuru', 'Mysuru', 'state-29', 0),
  ('city-nadiad', 'Nadiad', 'state-24', 0),
  ('city-nagpur', 'Nagpur', 'state-27', 0),
  ('city-nashik', 'Nashik', 'state-27', 0),
  ('city-navi-mumbai', 'Navi Mumbai', 'state-27', 0),
  ('city-navsari', 'Navsari', 'state-24', 0),
  ('city-new-delhi', 'New Delhi', 'state-07', 0),
  ('city-nizamabad', 'Nizamabad', 'state-36', 0),
  ('city-noida', 'Noida', 'state-09', 0),
  ('city-patiala', 'Patiala', 'state-03', 0),
  ('city-patna', 'Patna', 'state-10', 0),
  ('city-porbandar', 'Porbandar', 'state-24', 0),
  ('city-pune', 'Pune', 'state-27', 0),
  ('city-raipur', 'Raipur', 'state-22', 0),
  ('city-rajkot', 'Rajkot', 'state-24', 0),
  ('city-ranchi', 'Ranchi', 'state-20', 0),
  ('city-rewa', 'Rewa', 'state-23', 0),
  ('city-rohtak', 'Rohtak', 'state-06', 0),
  ('city-salem', 'Salem', 'state-33', 0),
  ('city-sangli', 'Sangli', 'state-27', 0),
  ('city-shimla', 'Shimla', 'state-02', 0),
  ('city-sikar', 'Sikar', 'state-08', 0),
  ('city-siliguri', 'Siliguri', 'state-19', 0),
  ('city-solapur', 'Solapur', 'state-27', 0),
  ('city-surat', 'Surat', 'state-24', 0),
  ('city-surendranagar', 'Surendranagar', 'state-24', 0),
  ('city-thane', 'Thane', 'state-27', 0),
  ('city-thiruvananthapuram', 'Thiruvananthapuram', 'state-32', 0),
  ('city-tiruchirappalli', 'Tiruchirappalli', 'state-33', 0),
  ('city-tirunelveli', 'Tirunelveli', 'state-33', 0),
  ('city-udaipur', 'Udaipur', 'state-08', 0),
  ('city-ujjain', 'Ujjain', 'state-23', 0),
  ('city-vadodara', 'Vadodara', 'state-24', 0),
  ('city-vapi', 'Vapi', 'state-24', 0),
  ('city-varanasi', 'Varanasi', 'state-09', 0),
  ('city-vasai', 'Vasai', 'state-27', 0),
  ('city-vijayawada', 'Vijayawada', 'state-37', 0),
  ('city-visakhapatnam', 'Visakhapatnam', 'state-37', 0),
  ('city-wankaner', 'Wankaner', 'state-24', 0),
  ('city-warangal', 'Warangal', 'state-36', 0);

INSERT INTO st_products (id, code, name, board_type, thickness_mm, size, category, unit_price_paise, stock_status, description) VALUES
  ('prod-osb-12-8x4',  'OSB-12-8X4',  'OSB 12mm Standard', 'OSB',         12, '8x4 ft', 'Standard',  85000, 'Available', 'Standard OSB board 12mm'),
  ('prod-osb-18-8x4',  'OSB-18-8X4',  'OSB 18mm Premium',  'OSB',         18, '8x4 ft', 'Premium',  120000, 'Available', 'Premium OSB 18mm thick'),
  ('prod-sosb-15-8x4', 'SOSB-15-8X4', 'S-OSB 15mm',        'S-OSB',       15, '8x4 ft', 'Standard', 105000, 'Available', 'Structural OSB 15mm'),
  ('prod-mdo-12-8x4',  'MDO-12-8X4',  'MDO 12mm Board',    'MDO',         12, '8x4 ft', 'Standard',  95000, 'Limited',   'Medium Density Overlay'),
  ('prod-hyb-18-8x4',  'HYB-18-8X4',  'Hybrid 18mm',       'Hybrid',      18, '8x4 ft', 'Premium',  135000, 'Available', 'Hybrid engineered board'),
  ('prod-cv-06-8x4',   'CV-06-8X4',   'Core Veneer 6mm',   'Core Veneer',  6, '8x4 ft', 'Standard',  65000, 'Available', 'Core veneer sheet');

-- Values are JSON. These are the legacy S.settings defaults. Role permissions go in st_role_permissions (0004).
INSERT INTO st_settings (key, value) VALUES
  ('company.name',           '"Strandply LLP"'),
  ('company.llpin',          '"AAP-7300"'),
  ('company.address_line',   '"Wankaner, Morbi, Gujarat"'),
  ('company.phone',          '""'),
  ('company.gst',            '""'),
  ('sheets.spreadsheet_id',  '""'),
  ('sheets.webapp_url',      '""'),
  ('sheets.interval_min',    '0'),
  ('sheets.last_sync_at',    'null');

INSERT INTO st_counters (name, last_value) VALUES
  ('REQ', 0),
  ('DSP', 0);
