// ════════════════════════════════════════════════════════════════════
// DEV ONLY demo data: the legacy SampleTrack seedData(), re-linked by id.
// Loaded only with the dev users (never in production, never in a migration).
// Legacy "mkt" / "by" names that aren't users (Suresh Kumar, Raj Verma) are kept in remarks.
// Mapping them to people is an open question (docs/sampletrack-spec.md §15).
// ════════════════════════════════════════════════════════════════════
import type { Courier, Dispatch, DispatchHistoryEntry, Party, SampleRequest, SampleRequestItem } from '../contracts/sampletrack';

const audit = (at: string) => ({ createdBy: null, createdAt: at, updatedAt: at, deletedAt: null });
const T = '2025-04-01T04:00:00.000Z';
const MKT = 'dev-user-marketing'; // "Ankit Patel" in the legacy data

export const DEMO_PARTIES: Party[] = [
  {
    id: 'demo-party-gfw',
    name: 'Gujarat Furniture Works',
    contact: 'Rajan Shah',
    mobile: '9876543210',
    email: 'rajan@gfw.com',
    gst: '24AAACG1234F1Z5',
    address: 'Plot 45, Gondal Rd, GIDC',
    city: 'Rajkot',
    state: 'Gujarat',
    pin: '360001',
    industry: 'Furniture',
    type: 'Existing Customer',
    assignedUserId: MKT,
    remarks: 'VIP client',
    ...audit(T),
  },
  {
    id: 'demo-party-mic',
    name: 'Mumbai Interior Co.',
    contact: 'Priya Mehta',
    mobile: '9867543210',
    email: 'priya@mic.com',
    gst: '27AAACM5678G1Z2',
    address: 'Shop 12, Infinity Mall, Andheri West',
    city: 'Mumbai',
    state: 'Maharashtra',
    pin: '400058',
    industry: 'Interior Design',
    type: 'Existing Customer',
    assignedUserId: null,
    remarks: 'High volume. Legacy owner: Suresh Kumar',
    ...audit(T),
  },
  {
    id: 'demo-party-dcl',
    name: 'Delhi Construction Ltd',
    contact: 'Anil Kumar',
    mobile: '9898765432',
    email: 'anil@dcl.com',
    gst: '07AAACD9012H1Z8',
    address: 'Office 5, Connaught Place',
    city: 'New Delhi',
    state: 'Delhi',
    pin: '110001',
    industry: 'Construction',
    type: 'New Lead',
    assignedUserId: MKT,
    remarks: 'First contact done',
    ...audit(T),
  },
  {
    id: 'demo-party-ptc',
    name: 'Pune Traders & Co.',
    contact: 'Sneha Joshi',
    mobile: '9765432109',
    email: 'sneha@ptc.com',
    gst: '27AAACP3456I1Z6',
    address: 'Gala 7, Hadapsar MIDC',
    city: 'Pune',
    state: 'Maharashtra',
    pin: '411013',
    industry: 'Trader / Dealer',
    type: 'Existing Customer',
    assignedUserId: null,
    remarks: 'Regular buyer. Legacy owner: Raj Verma',
    ...audit(T),
  },
  {
    id: 'demo-party-bas',
    name: 'Bengaluru Arch Studio',
    contact: 'Vikram Rao',
    mobile: '9654321098',
    email: 'vikram@bas.com',
    gst: '29AAACB7890J1Z4',
    address: 'No 24, 1st Cross, Koramangala',
    city: 'Bengaluru',
    state: 'Karnataka',
    pin: '560034',
    industry: 'Architect',
    type: 'New Lead',
    assignedUserId: null,
    remarks: 'Interested in S-OSB. Legacy owner: Suresh Kumar',
    ...audit(T),
  },
];

export const DEMO_COURIERS: Courier[] = [
  {
    id: 'demo-courier-bluedart',
    name: 'Blue Dart',
    type: 'Courier',
    contact: 'Sales Team',
    mobile: '1860-233-1234',
    email: 'sales@bluedart.com',
    coverage: 'Pan India',
    trackingUrlTemplate: 'https://www.bluedart.com/tracking?trackfor={tracking}',
    rating: 5,
    status: 'Active',
    remarks: 'Premium courier',
    ...audit(T),
  },
  {
    id: 'demo-courier-dtdc',
    name: 'DTDC',
    type: 'Courier',
    contact: 'Regional Mgr',
    mobile: '1800-103-3832',
    email: 'cs@dtdc.com',
    coverage: 'Pan India',
    trackingUrlTemplate: 'https://www.dtdc.in/tracking.asp?REF_NO={tracking}',
    rating: 4,
    status: 'Active',
    remarks: 'Cost-effective',
    ...audit(T),
  },
  {
    id: 'demo-courier-delhivery',
    name: 'Delhivery',
    type: 'Courier',
    contact: 'Key Accounts',
    mobile: '9999-1234-56',
    email: 'support@delhivery.com',
    coverage: 'Pan India',
    trackingUrlTemplate: 'https://www.delhivery.com/track/package/{tracking}',
    rating: 4,
    status: 'Active',
    remarks: 'Good for heavy',
    ...audit(T),
  },
  {
    id: 'demo-courier-gt',
    name: 'Gujarat Transport',
    type: 'Transport',
    contact: 'Kamlesh Bhai',
    mobile: '9876500001',
    email: 'gt@gmail.com',
    coverage: 'Gujarat, Maharashtra',
    trackingUrlTemplate: null,
    rating: 4,
    status: 'Active',
    remarks: 'Reliable for bulk',
    ...audit(T),
  },
  {
    id: 'demo-courier-rr',
    name: 'Rajasthan Roadways',
    type: 'Transport',
    contact: 'Shyam',
    mobile: '9845600002',
    email: null,
    coverage: 'Rajasthan, Gujarat',
    trackingUrlTemplate: null,
    rating: 3,
    status: 'Active',
    remarks: null,
    ...audit(T),
  },
];

const req = (
  n: number,
  partyId: string,
  date: string,
  over: Pick<SampleRequest, 'purpose' | 'priority' | 'requiredDispatchDate' | 'remarks' | 'status'>,
  requestedByUserId: string | null,
): SampleRequest => ({
  id: `demo-req-${n}`,
  reqNo: `REQ-${String(n).padStart(4, '0')}`,
  date,
  partyId,
  requestedByUserId,
  approvedBy: null,
  approvedAt: null,
  ...over,
  ...audit(`${date}T04:00:00.000Z`),
});

export const DEMO_REQUESTS: SampleRequest[] = [
  req(
    1,
    'demo-party-gfw',
    '2025-04-05',
    {
      purpose: 'Client Exhibition',
      priority: 'High',
      requiredDispatchDate: '2025-04-10',
      remarks: 'Urgent trade fair',
      status: 'Delivered',
    },
    MKT,
  ),
  req(
    2,
    'demo-party-mic',
    '2025-04-12',
    {
      purpose: 'Product Testing',
      priority: 'Normal',
      requiredDispatchDate: '2025-04-20',
      remarks: 'Test required',
      status: 'Approved',
    },
    null,
  ),
  req(
    3,
    'demo-party-dcl',
    '2025-04-15',
    {
      purpose: 'New Customer Demo',
      priority: 'Medium',
      requiredDispatchDate: '2025-04-22',
      remarks: 'First-time customer',
      status: 'Pending',
    },
    MKT,
  ),
  req(
    4,
    'demo-party-ptc',
    '2025-04-18',
    {
      purpose: 'Regular Supply',
      priority: 'Normal',
      requiredDispatchDate: '2025-04-25',
      remarks: null,
      status: 'Dispatched',
    },
    null,
  ),
  req(
    5,
    'demo-party-bas',
    '2025-04-20',
    {
      purpose: 'Architect Presentation',
      priority: 'High',
      requiredDispatchDate: '2025-04-26',
      remarks: 'High-value lead',
      status: 'Pending',
    },
    null,
  ),
];

const item = (
  n: number,
  line: number,
  productId: string,
  productName: string,
  board: string,
  thickness: string,
  qty: number,
): SampleRequestItem => ({
  id: `demo-req-${n}-${line}`,
  requestId: `demo-req-${n}`,
  lineNo: line,
  productId,
  productName,
  board,
  thickness,
  size: '8x4 ft',
  qtyValue: qty,
  qtyUnit: 'sheets',
  qtyRaw: `${qty} sheets`,
  ...audit(T),
});

export const DEMO_REQUEST_ITEMS: SampleRequestItem[] = [
  item(1, 1, 'prod-osb-18-8x4', 'OSB 18mm Premium', 'OSB', '18mm', 5),
  item(1, 2, 'prod-sosb-15-8x4', 'S-OSB 15mm', 'S-OSB', '15mm', 2),
  item(2, 1, 'prod-sosb-15-8x4', 'S-OSB 15mm', 'S-OSB', '15mm', 10),
  item(3, 1, 'prod-mdo-12-8x4', 'MDO 12mm Board', 'MDO', '12mm', 3),
  item(3, 2, 'prod-osb-12-8x4', 'OSB 12mm Standard', 'OSB', '12mm', 5),
  item(4, 1, 'prod-osb-12-8x4', 'OSB 12mm Standard', 'OSB', '12mm', 8),
  item(5, 1, 'prod-hyb-18-8x4', 'Hybrid 18mm', 'Hybrid', '18mm', 2),
  item(5, 2, 'prod-mdo-12-8x4', 'MDO 12mm Board', 'MDO', '12mm', 3),
];

const dsp = (
  n: number,
  over: Omit<Dispatch, 'id' | 'dspNo' | 'createdBy' | 'createdAt' | 'updatedAt' | 'deletedAt' | 'courierNameManual'>,
): Dispatch => ({
  id: `demo-dsp-${n}`,
  dspNo: `DSP-${String(n).padStart(4, '0')}`,
  courierNameManual: null,
  ...over,
  ...audit(`${over.date}T04:00:00.000Z`),
});

export const DEMO_DISPATCHES: Dispatch[] = [
  dsp(1, {
    date: '2025-04-06',
    partyId: 'demo-party-gfw',
    mode: 'Courier',
    courierId: 'demo-courier-bluedart',
    trackingNo: 'BD123456789',
    vehicleNo: null,
    driverDetails: null,
    expectedDeliveryDate: '2025-04-08',
    freightPaise: 45000,
    weightKg: 25,
    dimensions: '120x90x20cm',
    productDescription: 'OSB 18mm+S-OSB 15mm — 7 sheets',
    linkedRequestId: 'demo-req-1',
    remarks: 'On time',
    status: 'Delivered',
  }),
  dsp(2, {
    date: '2025-04-13',
    partyId: 'demo-party-mic',
    mode: 'Transport',
    courierId: 'demo-courier-gt',
    trackingNo: 'GT987654321',
    vehicleNo: 'GJ-33-T-5678',
    driverDetails: 'Kamlesh 9876543210',
    expectedDeliveryDate: '2025-04-16',
    freightPaise: 120000,
    weightKg: 80,
    dimensions: '240x120x30cm',
    productDescription: 'S-OSB 15mm — 10 sheets',
    linkedRequestId: 'demo-req-2',
    remarks: null,
    status: 'In Transit',
  }),
  dsp(3, {
    date: '2025-04-19',
    partyId: 'demo-party-ptc',
    mode: 'Courier',
    courierId: 'demo-courier-dtdc',
    trackingNo: 'DTDC556677889',
    vehicleNo: null,
    driverDetails: null,
    expectedDeliveryDate: '2025-04-22',
    freightPaise: 68000,
    weightKg: 40,
    dimensions: '90x60x25cm',
    productDescription: 'OSB 12mm — 8 sheets',
    linkedRequestId: 'demo-req-4',
    remarks: 'Stuck at hub',
    status: 'Delayed',
  }),
];

// Legacy dispatch history (times were IST wall clock, stored here as UTC).
const hist = (n: number, i: number, status: DispatchHistoryEntry['status'], istLocal: string): DispatchHistoryEntry => {
  const at = new Date(`${istLocal}:00+05:30`).toISOString();
  return { id: `demo-dsp-${n}-h${i}`, dispatchId: `demo-dsp-${n}`, status, changedBy: null, changedAt: at, note: null, ...audit(at) };
};

export const DEMO_DISPATCH_HISTORY: DispatchHistoryEntry[] = [
  hist(1, 1, 'Packed', '2025-04-06T10:00'),
  hist(1, 2, 'Dispatched', '2025-04-06T14:00'),
  hist(1, 3, 'In Transit', '2025-04-07T09:00'),
  hist(1, 4, 'Delivered', '2025-04-08T11:30'),
  hist(2, 1, 'Approved', '2025-04-13T09:00'),
  hist(2, 2, 'Packed', '2025-04-13T13:00'),
  hist(2, 3, 'Dispatched', '2025-04-14T08:00'),
  hist(2, 4, 'In Transit', '2025-04-14T16:00'),
  hist(3, 1, 'Dispatched', '2025-04-19T15:00'),
  hist(3, 2, 'In Transit', '2025-04-20T10:00'),
  hist(3, 3, 'Delayed', '2025-04-22T18:00'),
];
