// GENERATED from db/migrations/0003_sampletrack_seed.sql. Do not edit by hand.
// Reference data that every environment has: the memory backend loads it, and D1 gets it from the migration.
import type { City, Product, State } from '../contracts/sampletrack';

type Ref<T> = Omit<T, 'createdBy' | 'createdAt' | 'updatedAt' | 'deletedAt'>;

export const REF_STATES: State[] = [
  {
    id: 'state-01',
    name: 'Jammu & Kashmir',
    gstCode: '01',
    kind: 'UT',
  },
  {
    id: 'state-02',
    name: 'Himachal Pradesh',
    gstCode: '02',
    kind: 'State',
  },
  {
    id: 'state-03',
    name: 'Punjab',
    gstCode: '03',
    kind: 'State',
  },
  {
    id: 'state-04',
    name: 'Chandigarh',
    gstCode: '04',
    kind: 'UT',
  },
  {
    id: 'state-05',
    name: 'Uttarakhand',
    gstCode: '05',
    kind: 'State',
  },
  {
    id: 'state-06',
    name: 'Haryana',
    gstCode: '06',
    kind: 'State',
  },
  {
    id: 'state-07',
    name: 'Delhi',
    gstCode: '07',
    kind: 'UT',
  },
  {
    id: 'state-08',
    name: 'Rajasthan',
    gstCode: '08',
    kind: 'State',
  },
  {
    id: 'state-09',
    name: 'Uttar Pradesh',
    gstCode: '09',
    kind: 'State',
  },
  {
    id: 'state-10',
    name: 'Bihar',
    gstCode: '10',
    kind: 'State',
  },
  {
    id: 'state-11',
    name: 'Sikkim',
    gstCode: '11',
    kind: 'State',
  },
  {
    id: 'state-12',
    name: 'Arunachal Pradesh',
    gstCode: '12',
    kind: 'State',
  },
  {
    id: 'state-13',
    name: 'Nagaland',
    gstCode: '13',
    kind: 'State',
  },
  {
    id: 'state-14',
    name: 'Manipur',
    gstCode: '14',
    kind: 'State',
  },
  {
    id: 'state-15',
    name: 'Mizoram',
    gstCode: '15',
    kind: 'State',
  },
  {
    id: 'state-16',
    name: 'Tripura',
    gstCode: '16',
    kind: 'State',
  },
  {
    id: 'state-17',
    name: 'Meghalaya',
    gstCode: '17',
    kind: 'State',
  },
  {
    id: 'state-18',
    name: 'Assam',
    gstCode: '18',
    kind: 'State',
  },
  {
    id: 'state-19',
    name: 'West Bengal',
    gstCode: '19',
    kind: 'State',
  },
  {
    id: 'state-20',
    name: 'Jharkhand',
    gstCode: '20',
    kind: 'State',
  },
  {
    id: 'state-21',
    name: 'Odisha',
    gstCode: '21',
    kind: 'State',
  },
  {
    id: 'state-22',
    name: 'Chhattisgarh',
    gstCode: '22',
    kind: 'State',
  },
  {
    id: 'state-23',
    name: 'Madhya Pradesh',
    gstCode: '23',
    kind: 'State',
  },
  {
    id: 'state-24',
    name: 'Gujarat',
    gstCode: '24',
    kind: 'State',
  },
  {
    id: 'state-26',
    name: 'Dadra & Nagar Haveli and Daman & Diu',
    gstCode: '26',
    kind: 'UT',
  },
  {
    id: 'state-27',
    name: 'Maharashtra',
    gstCode: '27',
    kind: 'State',
  },
  {
    id: 'state-29',
    name: 'Karnataka',
    gstCode: '29',
    kind: 'State',
  },
  {
    id: 'state-30',
    name: 'Goa',
    gstCode: '30',
    kind: 'State',
  },
  {
    id: 'state-31',
    name: 'Lakshadweep',
    gstCode: '31',
    kind: 'UT',
  },
  {
    id: 'state-32',
    name: 'Kerala',
    gstCode: '32',
    kind: 'State',
  },
  {
    id: 'state-33',
    name: 'Tamil Nadu',
    gstCode: '33',
    kind: 'State',
  },
  {
    id: 'state-34',
    name: 'Puducherry',
    gstCode: '34',
    kind: 'UT',
  },
  {
    id: 'state-35',
    name: 'Andaman & Nicobar Islands',
    gstCode: '35',
    kind: 'UT',
  },
  {
    id: 'state-36',
    name: 'Telangana',
    gstCode: '36',
    kind: 'State',
  },
  {
    id: 'state-37',
    name: 'Andhra Pradesh',
    gstCode: '37',
    kind: 'State',
  },
  {
    id: 'state-38',
    name: 'Ladakh',
    gstCode: '38',
    kind: 'UT',
  },
];

export const REF_CITIES: Ref<City>[] = [
  {
    id: 'city-agra',
    city: 'Agra',
    stateId: 'state-09',
    isCustom: false,
  },
  {
    id: 'city-ahmedabad',
    city: 'Ahmedabad',
    stateId: 'state-24',
    isCustom: false,
  },
  {
    id: 'city-ajmer',
    city: 'Ajmer',
    stateId: 'state-08',
    isCustom: false,
  },
  {
    id: 'city-allahabad',
    city: 'Allahabad',
    stateId: 'state-09',
    isCustom: false,
  },
  {
    id: 'city-ambala',
    city: 'Ambala',
    stateId: 'state-06',
    isCustom: false,
  },
  {
    id: 'city-amravati',
    city: 'Amravati',
    stateId: 'state-27',
    isCustom: false,
  },
  {
    id: 'city-amreli',
    city: 'Amreli',
    stateId: 'state-24',
    isCustom: false,
  },
  {
    id: 'city-amritsar',
    city: 'Amritsar',
    stateId: 'state-03',
    isCustom: false,
  },
  {
    id: 'city-anand',
    city: 'Anand',
    stateId: 'state-24',
    isCustom: false,
  },
  {
    id: 'city-ankleshwar',
    city: 'Ankleshwar',
    stateId: 'state-24',
    isCustom: false,
  },
  {
    id: 'city-asansol',
    city: 'Asansol',
    stateId: 'state-19',
    isCustom: false,
  },
  {
    id: 'city-aurangabad',
    city: 'Aurangabad',
    stateId: 'state-27',
    isCustom: false,
  },
  {
    id: 'city-bareilly',
    city: 'Bareilly',
    stateId: 'state-09',
    isCustom: false,
  },
  {
    id: 'city-belagavi',
    city: 'Belagavi',
    stateId: 'state-29',
    isCustom: false,
  },
  {
    id: 'city-bengaluru',
    city: 'Bengaluru',
    stateId: 'state-29',
    isCustom: false,
  },
  {
    id: 'city-bhagalpur',
    city: 'Bhagalpur',
    stateId: 'state-10',
    isCustom: false,
  },
  {
    id: 'city-bharuch',
    city: 'Bharuch',
    stateId: 'state-24',
    isCustom: false,
  },
  {
    id: 'city-bhavnagar',
    city: 'Bhavnagar',
    stateId: 'state-24',
    isCustom: false,
  },
  {
    id: 'city-bhilwara',
    city: 'Bhilwara',
    stateId: 'state-08',
    isCustom: false,
  },
  {
    id: 'city-bhopal',
    city: 'Bhopal',
    stateId: 'state-23',
    isCustom: false,
  },
  {
    id: 'city-bhubaneswar',
    city: 'Bhubaneswar',
    stateId: 'state-21',
    isCustom: false,
  },
  {
    id: 'city-bhuj',
    city: 'Bhuj',
    stateId: 'state-24',
    isCustom: false,
  },
  {
    id: 'city-bikaner',
    city: 'Bikaner',
    stateId: 'state-08',
    isCustom: false,
  },
  {
    id: 'city-chandigarh',
    city: 'Chandigarh',
    stateId: 'state-04',
    isCustom: false,
  },
  {
    id: 'city-chennai',
    city: 'Chennai',
    stateId: 'state-33',
    isCustom: false,
  },
  {
    id: 'city-coimbatore',
    city: 'Coimbatore',
    stateId: 'state-33',
    isCustom: false,
  },
  {
    id: 'city-dehradun',
    city: 'Dehradun',
    stateId: 'state-05',
    isCustom: false,
  },
  {
    id: 'city-delhi',
    city: 'Delhi',
    stateId: 'state-07',
    isCustom: false,
  },
  {
    id: 'city-dombivali',
    city: 'Dombivali',
    stateId: 'state-27',
    isCustom: false,
  },
  {
    id: 'city-durgapur',
    city: 'Durgapur',
    stateId: 'state-19',
    isCustom: false,
  },
  {
    id: 'city-faridabad',
    city: 'Faridabad',
    stateId: 'state-06',
    isCustom: false,
  },
  {
    id: 'city-gandhinagar',
    city: 'Gandhinagar',
    stateId: 'state-24',
    isCustom: false,
  },
  {
    id: 'city-gaya',
    city: 'Gaya',
    stateId: 'state-10',
    isCustom: false,
  },
  {
    id: 'city-ghaziabad',
    city: 'Ghaziabad',
    stateId: 'state-09',
    isCustom: false,
  },
  {
    id: 'city-gondal',
    city: 'Gondal',
    stateId: 'state-24',
    isCustom: false,
  },
  {
    id: 'city-greater-noida',
    city: 'Greater Noida',
    stateId: 'state-09',
    isCustom: false,
  },
  {
    id: 'city-gurgaon',
    city: 'Gurgaon',
    stateId: 'state-06',
    isCustom: false,
  },
  {
    id: 'city-guwahati',
    city: 'Guwahati',
    stateId: 'state-18',
    isCustom: false,
  },
  {
    id: 'city-gwalior',
    city: 'Gwalior',
    stateId: 'state-23',
    isCustom: false,
  },
  {
    id: 'city-howrah',
    city: 'Howrah',
    stateId: 'state-19',
    isCustom: false,
  },
  {
    id: 'city-hubballi',
    city: 'Hubballi',
    stateId: 'state-29',
    isCustom: false,
  },
  {
    id: 'city-hyderabad',
    city: 'Hyderabad',
    stateId: 'state-36',
    isCustom: false,
  },
  {
    id: 'city-indore',
    city: 'Indore',
    stateId: 'state-23',
    isCustom: false,
  },
  {
    id: 'city-jabalpur',
    city: 'Jabalpur',
    stateId: 'state-23',
    isCustom: false,
  },
  {
    id: 'city-jaipur',
    city: 'Jaipur',
    stateId: 'state-08',
    isCustom: false,
  },
  {
    id: 'city-jalandhar',
    city: 'Jalandhar',
    stateId: 'state-03',
    isCustom: false,
  },
  {
    id: 'city-jamnagar',
    city: 'Jamnagar',
    stateId: 'state-24',
    isCustom: false,
  },
  {
    id: 'city-jodhpur',
    city: 'Jodhpur',
    stateId: 'state-08',
    isCustom: false,
  },
  {
    id: 'city-junagadh',
    city: 'Junagadh',
    stateId: 'state-24',
    isCustom: false,
  },
  {
    id: 'city-kalaburagi',
    city: 'Kalaburagi',
    stateId: 'state-29',
    isCustom: false,
  },
  {
    id: 'city-kalyan',
    city: 'Kalyan',
    stateId: 'state-27',
    isCustom: false,
  },
  {
    id: 'city-kanpur',
    city: 'Kanpur',
    stateId: 'state-09',
    isCustom: false,
  },
  {
    id: 'city-karimnagar',
    city: 'Karimnagar',
    stateId: 'state-36',
    isCustom: false,
  },
  {
    id: 'city-khammam',
    city: 'Khammam',
    stateId: 'state-36',
    isCustom: false,
  },
  {
    id: 'city-kochi',
    city: 'Kochi',
    stateId: 'state-32',
    isCustom: false,
  },
  {
    id: 'city-kolhapur',
    city: 'Kolhapur',
    stateId: 'state-27',
    isCustom: false,
  },
  {
    id: 'city-kolkata',
    city: 'Kolkata',
    stateId: 'state-19',
    isCustom: false,
  },
  {
    id: 'city-kota',
    city: 'Kota',
    stateId: 'state-08',
    isCustom: false,
  },
  {
    id: 'city-kozhikode',
    city: 'Kozhikode',
    stateId: 'state-32',
    isCustom: false,
  },
  {
    id: 'city-latur',
    city: 'Latur',
    stateId: 'state-27',
    isCustom: false,
  },
  {
    id: 'city-lucknow',
    city: 'Lucknow',
    stateId: 'state-09',
    isCustom: false,
  },
  {
    id: 'city-ludhiana',
    city: 'Ludhiana',
    stateId: 'state-03',
    isCustom: false,
  },
  {
    id: 'city-madurai',
    city: 'Madurai',
    stateId: 'state-33',
    isCustom: false,
  },
  {
    id: 'city-mangaluru',
    city: 'Mangaluru',
    stateId: 'state-29',
    isCustom: false,
  },
  {
    id: 'city-meerut',
    city: 'Meerut',
    stateId: 'state-09',
    isCustom: false,
  },
  {
    id: 'city-mehsana',
    city: 'Mehsana',
    stateId: 'state-24',
    isCustom: false,
  },
  {
    id: 'city-morbi',
    city: 'Morbi',
    stateId: 'state-24',
    isCustom: false,
  },
  {
    id: 'city-mumbai',
    city: 'Mumbai',
    stateId: 'state-27',
    isCustom: false,
  },
  {
    id: 'city-muzaffarpur',
    city: 'Muzaffarpur',
    stateId: 'state-10',
    isCustom: false,
  },
  {
    id: 'city-mysuru',
    city: 'Mysuru',
    stateId: 'state-29',
    isCustom: false,
  },
  {
    id: 'city-nadiad',
    city: 'Nadiad',
    stateId: 'state-24',
    isCustom: false,
  },
  {
    id: 'city-nagpur',
    city: 'Nagpur',
    stateId: 'state-27',
    isCustom: false,
  },
  {
    id: 'city-nashik',
    city: 'Nashik',
    stateId: 'state-27',
    isCustom: false,
  },
  {
    id: 'city-navi-mumbai',
    city: 'Navi Mumbai',
    stateId: 'state-27',
    isCustom: false,
  },
  {
    id: 'city-navsari',
    city: 'Navsari',
    stateId: 'state-24',
    isCustom: false,
  },
  {
    id: 'city-new-delhi',
    city: 'New Delhi',
    stateId: 'state-07',
    isCustom: false,
  },
  {
    id: 'city-nizamabad',
    city: 'Nizamabad',
    stateId: 'state-36',
    isCustom: false,
  },
  {
    id: 'city-noida',
    city: 'Noida',
    stateId: 'state-09',
    isCustom: false,
  },
  {
    id: 'city-patiala',
    city: 'Patiala',
    stateId: 'state-03',
    isCustom: false,
  },
  {
    id: 'city-patna',
    city: 'Patna',
    stateId: 'state-10',
    isCustom: false,
  },
  {
    id: 'city-porbandar',
    city: 'Porbandar',
    stateId: 'state-24',
    isCustom: false,
  },
  {
    id: 'city-pune',
    city: 'Pune',
    stateId: 'state-27',
    isCustom: false,
  },
  {
    id: 'city-raipur',
    city: 'Raipur',
    stateId: 'state-22',
    isCustom: false,
  },
  {
    id: 'city-rajkot',
    city: 'Rajkot',
    stateId: 'state-24',
    isCustom: false,
  },
  {
    id: 'city-ranchi',
    city: 'Ranchi',
    stateId: 'state-20',
    isCustom: false,
  },
  {
    id: 'city-rewa',
    city: 'Rewa',
    stateId: 'state-23',
    isCustom: false,
  },
  {
    id: 'city-rohtak',
    city: 'Rohtak',
    stateId: 'state-06',
    isCustom: false,
  },
  {
    id: 'city-salem',
    city: 'Salem',
    stateId: 'state-33',
    isCustom: false,
  },
  {
    id: 'city-sangli',
    city: 'Sangli',
    stateId: 'state-27',
    isCustom: false,
  },
  {
    id: 'city-shimla',
    city: 'Shimla',
    stateId: 'state-02',
    isCustom: false,
  },
  {
    id: 'city-sikar',
    city: 'Sikar',
    stateId: 'state-08',
    isCustom: false,
  },
  {
    id: 'city-siliguri',
    city: 'Siliguri',
    stateId: 'state-19',
    isCustom: false,
  },
  {
    id: 'city-solapur',
    city: 'Solapur',
    stateId: 'state-27',
    isCustom: false,
  },
  {
    id: 'city-surat',
    city: 'Surat',
    stateId: 'state-24',
    isCustom: false,
  },
  {
    id: 'city-surendranagar',
    city: 'Surendranagar',
    stateId: 'state-24',
    isCustom: false,
  },
  {
    id: 'city-thane',
    city: 'Thane',
    stateId: 'state-27',
    isCustom: false,
  },
  {
    id: 'city-thiruvananthapuram',
    city: 'Thiruvananthapuram',
    stateId: 'state-32',
    isCustom: false,
  },
  {
    id: 'city-tiruchirappalli',
    city: 'Tiruchirappalli',
    stateId: 'state-33',
    isCustom: false,
  },
  {
    id: 'city-tirunelveli',
    city: 'Tirunelveli',
    stateId: 'state-33',
    isCustom: false,
  },
  {
    id: 'city-udaipur',
    city: 'Udaipur',
    stateId: 'state-08',
    isCustom: false,
  },
  {
    id: 'city-ujjain',
    city: 'Ujjain',
    stateId: 'state-23',
    isCustom: false,
  },
  {
    id: 'city-vadodara',
    city: 'Vadodara',
    stateId: 'state-24',
    isCustom: false,
  },
  {
    id: 'city-vapi',
    city: 'Vapi',
    stateId: 'state-24',
    isCustom: false,
  },
  {
    id: 'city-varanasi',
    city: 'Varanasi',
    stateId: 'state-09',
    isCustom: false,
  },
  {
    id: 'city-vasai',
    city: 'Vasai',
    stateId: 'state-27',
    isCustom: false,
  },
  {
    id: 'city-vijayawada',
    city: 'Vijayawada',
    stateId: 'state-37',
    isCustom: false,
  },
  {
    id: 'city-visakhapatnam',
    city: 'Visakhapatnam',
    stateId: 'state-37',
    isCustom: false,
  },
  {
    id: 'city-wankaner',
    city: 'Wankaner',
    stateId: 'state-24',
    isCustom: false,
  },
  {
    id: 'city-warangal',
    city: 'Warangal',
    stateId: 'state-36',
    isCustom: false,
  },
];

export const REF_PRODUCTS: Ref<Product>[] = [
  {
    id: 'prod-osb-12-8x4',
    code: 'OSB-12-8X4',
    name: 'OSB 12mm Standard',
    boardType: 'OSB',
    thicknessMm: 12,
    size: '8x4 ft',
    category: 'Standard',
    unitPricePaise: 85000,
    stockStatus: 'Available',
    description: 'Standard OSB board 12mm',
  },
  {
    id: 'prod-osb-18-8x4',
    code: 'OSB-18-8X4',
    name: 'OSB 18mm Premium',
    boardType: 'OSB',
    thicknessMm: 18,
    size: '8x4 ft',
    category: 'Premium',
    unitPricePaise: 120000,
    stockStatus: 'Available',
    description: 'Premium OSB 18mm thick',
  },
  {
    id: 'prod-sosb-15-8x4',
    code: 'SOSB-15-8X4',
    name: 'S-OSB 15mm',
    boardType: 'S-OSB',
    thicknessMm: 15,
    size: '8x4 ft',
    category: 'Standard',
    unitPricePaise: 105000,
    stockStatus: 'Available',
    description: 'Structural OSB 15mm',
  },
  {
    id: 'prod-mdo-12-8x4',
    code: 'MDO-12-8X4',
    name: 'MDO 12mm Board',
    boardType: 'MDO',
    thicknessMm: 12,
    size: '8x4 ft',
    category: 'Standard',
    unitPricePaise: 95000,
    stockStatus: 'Limited',
    description: 'Medium Density Overlay',
  },
  {
    id: 'prod-hyb-18-8x4',
    code: 'HYB-18-8X4',
    name: 'Hybrid 18mm',
    boardType: 'Hybrid',
    thicknessMm: 18,
    size: '8x4 ft',
    category: 'Premium',
    unitPricePaise: 135000,
    stockStatus: 'Available',
    description: 'Hybrid engineered board',
  },
  {
    id: 'prod-cv-06-8x4',
    code: 'CV-06-8X4',
    name: 'Core Veneer 6mm',
    boardType: 'Core Veneer',
    thicknessMm: 6,
    size: '8x4 ft',
    category: 'Standard',
    unitPricePaise: 65000,
    stockStatus: 'Available',
    description: 'Core veneer sheet',
  },
];
