// Vendors module seed, from the legacy Vendor Portal defaults (dCat, dProd, dTnc, dV).
// Categories, products and T&C are reference data (also in db/migrations/0005_vendors.sql).
// The vendors themselves are DEV ONLY demo data.
import type { TncClause, Vendor, VendorCategory, VendorProduct } from '../contracts/vendors';

type Ref<T> = Omit<T, 'createdBy' | 'createdAt' | 'updatedAt' | 'deletedAt'>;

export const REF_VENDOR_CATEGORIES: Ref<VendorCategory>[] = [
  { id: 'vcat-raw-material', name: 'Raw Material', icon: '🪵', color: 'yellow', description: 'Strands, timber, veneer', sortOrder: 1, status: 'active', notes: null },
  { id: 'vcat-resin', name: 'Resin & Chemicals', icon: '🧪', color: 'indigo', description: 'MDI, PMDI, UF resin', sortOrder: 2, status: 'active', notes: null },
  { id: 'vcat-packaging', name: 'Packaging', icon: '📦', color: 'pink', description: 'Film, edge protectors', sortOrder: 3, status: 'active', notes: null },
  { id: 'vcat-transport', name: 'Transport', icon: '🚛', color: 'blue', description: 'Trucks and logistics', sortOrder: 4, status: 'active', notes: null },
  { id: 'vcat-maintenance', name: 'Maintenance', icon: '🔧', color: 'green', description: 'Press and machinery', sortOrder: 5, status: 'active', notes: null },
  { id: 'vcat-job-work', name: 'Job Work', icon: '🛠️', color: 'purple', description: 'Disposal and processing', sortOrder: 6, status: 'active', notes: null },
];

const product = (n: number, name: string, categoryId: string, unit: VendorProduct['unit'], hsn: string): Ref<VendorProduct> => ({
  id: `vprod-${String(n).padStart(3, '0')}`,
  code: `SPL-P-26-${String(n).padStart(3, '0')}`,
  name,
  categoryId,
  unit,
  altUnit: null,
  convFactor: null,
  hsn,
  gstRate: null,
  moq: null,
  leadTimeDays: null,
  description: null,
  notes: null,
});

export const REF_VENDOR_PRODUCTS: Ref<VendorProduct>[] = [
  product(1, 'Wax-Coated Strands', 'vcat-raw-material', 'MT', '4401'),
  product(2, 'Dry Strands', 'vcat-raw-material', 'MT', '4401'),
  product(3, 'Birch Face Veneer', 'vcat-raw-material', 'Sheets', '4408'),
  product(4, 'Core Veneer', 'vcat-raw-material', 'Sheets', '4408'),
  product(5, 'MDI Resin', 'vcat-resin', 'Drum', '3909'),
  product(6, 'PMDI Binder', 'vcat-resin', 'Drum', '3909'),
  product(7, 'Urea Formaldehyde Resin', 'vcat-resin', 'Drum', '3909'),
  product(8, 'Wax Emulsion', 'vcat-resin', 'Can', '3404'),
  product(9, 'Stretch Film Roll', 'vcat-packaging', 'Roll', '3920'),
  product(10, 'Edge Protectors', 'vcat-packaging', 'Nos', '4819'),
  product(11, 'FTL Truck (10T)', 'vcat-transport', 'Trip', '9965'),
  product(12, 'Container (22T)', 'vcat-transport', 'Trip', '9965'),
  product(13, 'Press Servicing', 'vcat-maintenance', 'Visit', '9987'),
  product(14, 'Resin Waste Disposal', 'vcat-job-work', 'Trip', '9994'),
];
/** Counter row that matches the seeded product codes. */
export const VENDOR_PRODUCT_COUNTER = { name: 'VP-26', lastValue: REF_VENDOR_PRODUCTS.length };

export const REF_TNC: Ref<TncClause>[] = [
  {
    id: 'tnc-payment',
    title: 'Payment Terms',
    category: 'Payment',
    version: '1.0',
    status: 'active',
    appliesTo: 'all',
    body: 'All invoices are payable within the agreed credit period from the date of invoice. Payments must be made by NEFT/RTGS/Cheque in favour of Strandply LLP. Late payments will attract interest at 18% per annum.',
    summary: 'Payment within credit period; 18% interest on delays.',
    notes: null,
  },
  {
    id: 'tnc-delivery',
    title: 'Delivery & Transportation',
    category: 'Delivery',
    version: '1.0',
    status: 'active',
    appliesTo: 'all',
    body: 'Delivery shall be made at the Strandply plant, Wankaner, Morbi, Gujarat unless otherwise specified. Risk of loss or damage passes to Strandply upon delivery at the plant gate. Vendor must provide valid e-way bill for all dispatches above Rs. 50,000.',
    summary: 'Delivery at Wankaner plant; e-way bill mandatory above Rs.50,000.',
    notes: null,
  },
  {
    id: 'tnc-quality',
    title: 'Quality & Inspection',
    category: 'Quality',
    version: '1.0',
    status: 'active',
    appliesTo: 'po',
    body: 'All materials are subject to inspection upon receipt. Strandply reserves the right to reject materials that do not conform to agreed specifications. Rejected materials must be replaced within 7 working days at the vendor cost.',
    summary: 'Inspection on receipt; rejection within 7 days at vendor cost.',
    notes: null,
  },
  {
    id: 'tnc-warranty',
    title: 'Warranty',
    category: 'Warranty',
    version: '1.0',
    status: 'active',
    appliesTo: 'all',
    body: 'Vendor warrants that all goods supplied are free from defects in material and workmanship and conform to the specifications agreed upon. Warranty period is 12 months from date of delivery.',
    summary: '12-month warranty from delivery date.',
    notes: null,
  },
  {
    id: 'tnc-confidentiality',
    title: 'Confidentiality',
    category: 'Legal',
    version: '1.0',
    status: 'active',
    appliesTo: 'vendor',
    body: 'The vendor agrees to keep all technical specifications, pricing, and business information of Strandply LLP strictly confidential and not to disclose the same to any third party without prior written consent.',
    summary: 'All Strandply information to be kept strictly confidential.',
    notes: null,
  },
];

/** Legacy Purchase ERP PO clauses (TC_MASTER) not already covered above; added with the Purchase module (0006). */
export const REF_PO_TNC: Ref<TncClause>[] = [
  { id: 'tnc-po-weight', title: 'Weight Variation', category: 'Quality', version: '1.0', status: 'active', appliesTo: 'po', body: 'Acceptable weight variation ±2%. Beyond that, debit/credit note will be issued.', summary: 'Weight variation over ±2% settled by debit/credit note.', notes: null },
  { id: 'tnc-po-delivery', title: 'Delivery Schedule', category: 'Delivery', version: '1.0', status: 'active', appliesTo: 'po', body: 'Delivery as per agreed schedule. Delay penalty 0.5% per week.', summary: 'Delay penalty 0.5% per week.', notes: null },
  { id: 'tnc-po-rate', title: 'Rate Revision', category: 'Payment', version: '1.0', status: 'active', appliesTo: 'po', body: 'Rates are fixed for the PO period. Any revision requires written consent.', summary: 'Rates fixed for the PO period.', notes: null },
  { id: 'tnc-po-gst', title: 'GST Compliance', category: 'Legal', version: '1.0', status: 'active', appliesTo: 'po', body: 'Vendor must provide valid GST invoice. ITC credit subject to vendor filing.', summary: 'Valid GST invoice required.', notes: null },
];

const blank: Omit<Vendor, 'id' | 'code' | 'name' | 'status' | 'categoryIds' | 'productIds' | 'createdAt' | 'updatedAt'> = {
  type: null,
  yearEstablished: null,
  contact: null,
  designation: null,
  phone: null,
  email: null,
  address: null,
  pincode: null,
  city: null,
  state: null,
  website: null,
  gst: null,
  pan: null,
  msme: null,
  paymentTerms: null,
  bank: null,
  accountNo: null,
  ifsc: null,
  rating: null,
  notes: null,
  submittedAt: null,
  approvedAt: null,
  approvedBy: null,
  activatedAt: null,
  activatedBy: null,
  blacklistReason: null,
  blacklistedAt: null,
  blacklistedBy: null,
  createdBy: null,
  deletedAt: null,
};

/** DEV ONLY. The legacy demo vendors (dV). */
export const DEMO_VENDORS: Vendor[] = [
  {
    ...blank,
    id: 'ven-nilgiri',
    code: 'SPL-VEN-25-001',
    name: 'Nilgiri Timber Pvt Ltd',
    type: 'Manufacturer',
    categoryIds: ['vcat-raw-material'],
    productIds: ['vprod-001', 'vprod-002'],
    contact: 'Rajesh Nair',
    phone: '9876543210',
    email: 'rajesh@nilgiri.com',
    city: 'Nagpur',
    state: 'Maharashtra',
    pincode: '440002',
    gst: '27AABCN1234F1Z5',
    paymentTerms: '45 Days',
    rating: 4,
    status: 'active',
    createdAt: '2024-11-10T09:00:00.000Z',
    updatedAt: '2024-11-12T10:00:00.000Z',
    submittedAt: '2024-11-10T09:00:00.000Z',
    approvedAt: '2024-11-12T10:00:00.000Z',
    activatedAt: '2024-11-12T10:00:00.000Z',
  },
  {
    ...blank,
    id: 'ven-hexion',
    code: 'SPL-VEN-25-002',
    name: 'Hexion Resins India',
    type: 'Distributor',
    categoryIds: ['vcat-resin'],
    productIds: ['vprod-005', 'vprod-006', 'vprod-008'],
    contact: 'Priya Sharma',
    phone: '9988001122',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400093',
    gst: '27AABHX5678G1Z3',
    paymentTerms: '30 Days',
    rating: 5,
    status: 'active',
    notes: 'Premium quality resins.',
    createdAt: '2024-10-05T09:00:00.000Z',
    updatedAt: '2024-10-07T10:00:00.000Z',
    submittedAt: '2024-10-05T09:00:00.000Z',
    approvedAt: '2024-10-07T10:00:00.000Z',
    activatedAt: '2024-10-07T10:00:00.000Z',
  },
  {
    ...blank,
    id: 'ven-packaging-world',
    code: 'SPL-VEN-25-003',
    name: 'Packaging World Morbi',
    type: 'Manufacturer',
    categoryIds: ['vcat-packaging'],
    productIds: ['vprod-009', 'vprod-010'],
    contact: 'Kiran Shah',
    phone: '9654321000',
    city: 'Morbi',
    state: 'Gujarat',
    pincode: '363641',
    paymentTerms: '30 Days',
    rating: 4,
    status: 'active',
    createdAt: '2025-02-01T09:00:00.000Z',
    updatedAt: '2025-02-03T09:00:00.000Z',
    submittedAt: '2025-02-01T09:00:00.000Z',
    approvedAt: '2025-02-03T09:00:00.000Z',
    activatedAt: '2025-02-03T09:00:00.000Z',
  },
  {
    ...blank,
    id: 'ven-gujarat-cargo',
    code: 'SPL-VEN-25-004',
    name: 'Gujarat Cargo Services',
    type: 'Transporter',
    categoryIds: ['vcat-transport'],
    productIds: ['vprod-011'],
    contact: 'Mahesh Patel',
    phone: '9123456780',
    city: 'Ahmedabad',
    state: 'Gujarat',
    paymentTerms: 'Against Delivery',
    rating: 4,
    status: 'active',
    createdAt: '2024-09-01T09:00:00.000Z',
    updatedAt: '2024-09-03T10:00:00.000Z',
    submittedAt: '2024-09-01T09:00:00.000Z',
    approvedAt: '2024-09-03T10:00:00.000Z',
    activatedAt: '2024-09-03T10:00:00.000Z',
  },
  {
    ...blank,
    id: 'ven-sunrise',
    code: 'SPL-VEN-25-005',
    name: 'Sunrise Timber Traders',
    type: 'Trader',
    categoryIds: ['vcat-raw-material'],
    productIds: ['vprod-001'],
    contact: 'Anil Verma',
    phone: '9765432100',
    city: 'Valsad',
    state: 'Gujarat',
    pincode: '396001',
    paymentTerms: '30 Days',
    rating: 3,
    status: 'pending',
    createdAt: '2025-05-10T09:00:00.000Z',
    updatedAt: '2025-05-10T09:00:00.000Z',
    submittedAt: '2025-05-10T09:00:00.000Z',
  },
  {
    ...blank,
    id: 'ven-basant',
    code: 'SPL-VEN-25-006',
    name: 'Basant Chemicals',
    type: 'Trader',
    categoryIds: ['vcat-resin'],
    productIds: ['vprod-005', 'vprod-007'],
    contact: 'Basant Agarwal',
    phone: '9000111222',
    city: 'Ankleshwar',
    state: 'Gujarat',
    paymentTerms: '30 Days',
    rating: 3,
    status: 'active',
    createdAt: '2025-01-12T09:00:00.000Z',
    updatedAt: '2025-01-14T10:00:00.000Z',
    submittedAt: '2025-01-12T09:00:00.000Z',
    approvedAt: '2025-01-14T10:00:00.000Z',
    activatedAt: '2025-01-14T10:00:00.000Z',
  },
  {
    ...blank,
    id: 'ven-cheap-fast',
    code: 'SPL-VEN-25-007',
    name: 'Cheap & Fast Packaging',
    type: 'Trader',
    categoryIds: ['vcat-packaging'],
    productIds: ['vprod-009'],
    contact: 'Unknown',
    city: 'Morbi',
    state: 'Gujarat',
    paymentTerms: 'Advance',
    rating: 1,
    status: 'blacklisted',
    blacklistReason: 'Substandard material - refused to refund.',
    blacklistedAt: '2025-02-20T10:00:00.000Z',
    createdAt: '2025-01-05T09:00:00.000Z',
    updatedAt: '2025-02-20T10:00:00.000Z',
    submittedAt: '2025-01-05T09:00:00.000Z',
  },
];

/** Default vendor e-mail settings (st_settings keys). */
export const DEFAULT_VENDOR_SETTINGS: Record<string, unknown> = {
  'vendors.email.from_name': 'Strandply LLP',
  'vendors.email.reply_to': '',
};
